### ISSUE TITLE
1. Web IDE

### ISSUE THREAD

**Issue by mihal** [mihal/tea-gallery#1]
Hello Kate,

your first task is here. Are you excited? Let's begin.

Before we start any hard work, you need to choose the IDE you want to use for the development.
You can search by yourself with keyword 'web application IDE' or you can pick one of this three
- [Visual Studio Code](https://code.visualstudio.com/) - this one should be quite good.
- [Atom](https://atom.io/) - developed by github itself. It does not look bad.
- [Netbeans](https://netbeans.apache.org/) - it seems netbeans is back again. Now financed and developed by Apache. I had lot of good experiences with this one. Hopefully it is still so good as it was.

All these IDEs are free. If you want to go for paid one, [IntelliJ](https://www.jetbrains.com/idea/) or [WebStorm](https://www.jetbrains.com/webstorm/) are the best choice.

Do the research, maybe try some of them and then let me know which one you will be using.
Good IDE hunting.

**Comment by knovakova** [comment]
I have chosen and installed VS Code (even though... Microsoft). I'm going through a tutorial - which will become even more useful once I have some code to practice on in my project.

**Comment by mihal** [comment]
Excellent Kate. I consider this task as complete. You can now proceed to task number 2.
