### ISSUE TITLE
2. SSH Key

### ISSUE THREAD

**Issue by mihal** [mihal/tea-gallery#2]
Hello Kate,

your next task is to add SSH key into GitHub to simplify communication from you local computer.
How to setup SSH key can be found [here](https://docs.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account). If you do not have SSH key generated yet, you can do so [this way](https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent). If you are not sure if you have it, [this](https://docs.github.com/en/github/authenticating-to-github/checking-for-existing-ssh-keys) should help you find it out. 

Happy setting.
M.

**Comment by knovakova** [comment]
Should I also add my generated key to the SSH agent?

**Comment by mihal** [comment]
If you have chosen key with paraphrase, you should. If not, it is optional.

**Comment by knovakova** [comment]
I have added the key into the SSH agent, and I also added it to GitHub. Is there any way I can check it is working correctly?

**Comment by mihal** [comment]
[GitHub Page -> How to test SSH connection](https://docs.github.com/en/github/authenticating-to-github/testing-your-ssh-connection).

Happy testing

**Comment by knovakova** [comment]
Yes, it is working correctly. I'm awaiting further instructions...

**Comment by mihal** [comment]
Great work. You can proceed to task number 3.
