### ISSUE TITLE
3. Git Client + UI

### ISSUE THREAD

**Issue by mihal** [mihal/tea-gallery#3]
Hello Kate,

After you configured your SSH key into GitHub, we can now proceed to clone our repository to your local computer.
For that you will need git. Here are tasks for you:
1. Have Git client installed
   1. Check if you have already git installed by going into terminal and writing `git --version`
   2. If you do not have install it from [here](https://git-scm.com/download/linux)
2. Select GIT UI client if you do not want to use the terminal only
   1. Check [this](https://git-scm.com/download/gui/linux) where are listed git clients available on Linux
      1. GitKraken is considered to be good, maybe also SmartGit looks similar to the SourceTree.
   2. You can also use GitHub (VCS) integration inside Visual Studio Code. You can find more information in Code official sites or on youtube.
3. Clone tea-gallery repository into your local computer. Select target directory of your desire. Clone url can be found in code / code button.

Good luck,
M.

**Comment by knovakova** [comment]
I have git version 2.25.1. I have GitKraken installed. But I ended up cloning the repository via VS Code.

**Comment by mihal** [comment]
Good job. I will create the next task then.
