### ISSUE TITLE
4. Style Framework

### ISSUE THREAD

**Issue by mihal** [mihal/tea-gallery#4]
Hello Kate,

your another task will be to select a 'Style' framework for your tea gallery. Style frameworks are frameworks which provide you custom styling and components. You can then use these tools to build nice page without any effort.
Your first task is to chose one. You can search by yourself, the term 'frontend frameworks' can be used. Our page will be displaying photos in grids or as tiles so the framework should cover it. Probably the most popular is [Bootstrap](https://getbootstrap.com/docs/5.0/getting-started/introduction/). Also interesting one is [UIKit](https://getuikit.com/docs/introduction). Hopefully this two examples gives you a slight idea what you should be looking for.

Happy hunting.
M.

**Comment by knovakova** [comment]
I have chosen Bulma. The [documentation](https://bulma.io/documentation/) looks useful, it is visually appealing, and there is at least one [good tutorial](https://www.youtube.com/watch?v=IiPQYQT2-wg&ab_channel=TraversyMedia) for it (also covering [Emmet](https://emmet.io/)).

**Comment by mihal** [comment]
Cool Kate. Let's do some experimenting.
