### ISSUE TITLE
5. Hello World

### ISSUE THREAD

**Issue by mihal** [mihal/tea-gallery#5]
Hello Kate,

Coding part begins. So let's get started.
1. Create new git branch called hello-world
2. Create `index.html` file in root directory. Should be html5 complaint. VS Code should help you with that or google.
3. Integrate the selected style framework into the index.html file by following steps in How to install or Getting started. Usually it is just adding script tag with the framework library.
4. Add 'Site Under Construction' (or some other) text in the middle of the page.
5. Push the result into GitHub remote.

Happy coding
M,

**Comment by knovakova** [comment]
I did my best - but I remember almost nothing about CSS and nesting elements, so this is the best I could make it look.

**Comment by mihal** [comment]
Great job Kate. I know it was a fight but you did good.
