### ISSUE TITLE
6. Hello World - Basics

### ISSUE THREAD

**Issue by mihal** [mihal/tea-gallery#6]
Hello Kate,

let's have a step back and try do something similar without using any framework. We will be continue working with the index.html file inside hello-world git branch.
Here are your tasks:
1. Remove the framework dependencies
2. Add image to the background, i.e. whole page must be covered by single image. What image you choose is entirely up to you.
3. Add text in the middle of the page. It can be either 'Coming soon', 'Under Construction...' or something what you like.

To have some clue how it should look like, here is an [example](https://mihal.github.io/travel-gallery/). If you have any problem with the tasks, let me know and I will try to help you. 

PS: We will have multiple tasks in this topic so these three are just the beginning.

Good luck,
M.

**Comment by knovakova** [comment]
I have pushed the changes. I wouldn't have figured out how to center the text but I think I understand (at least) how your solution works. Maybe. Possibly.

**Comment by mihal** [comment]
It looks very nice. You did a good job.
Could you explain to me how it works? The centered container. :) 

M.

**Comment by mihal** [comment]
You doing very well. So let's continue.
1. Add footer to the bottom of the page
2. Then put inside centered &bull; Kate &bull; 2020
3. &bull; Kate should have one color and the &bull; 2020 another

Happy coding
M.

Good luck

**Comment by knovakova** [comment]
Finished!

**Comment by mihal** [comment]
Good job. Let's continue.
1. Add header to the top of the page
2. Add heading (hx tag) to the header with text 'Tea Gallery'. Text will be aligned to the left.
3. Add input type text and button to the right side of the header. Input and button will be next each other. Input will have placeholder saying Message and button will have label saying 'Send'. Between the right side of the page and button should be at least 2em space. (Hint: [Floating](https://www.w3schools.com/css/css_float.asp), [Possition](https://www.w3schools.com/css/css_positioning.asp) or [google ](https://www.google.com/search?q=css+div+position+right))

Good luck. You can do it.
M.

**Comment by knovakova** [comment]
Finished!

**Comment by mihal** [comment]
Good job Kate. Now we will do some clean up and little bit of Javascript.
1. create index.css file, move all styles inside the file and add the linkage to the script into index.html head
2. create index.js file and add linkage to the script into index.html head
3. create function handleButtonClick without any parameters. When the function is called it will take current value of the input on the index.html page. If is non-blank, it will display an alert with the input value.
4. make button call the function handleButtonClick on click

Good luck.
M.

**Comment by knovakova** [comment]
Finished!

**Comment by knovakova** [comment]
Now finished?

**Comment by mihal** [comment]
Yes, it is finished. Good job Kate.
You finished this task.
