### ISSUE TITLE
7. Hello Bootstrap

### ISSUE THREAD

**Issue by mihal** [mihal/tea-gallery#7]
Hello Kate,
I have a new task for you. We will now try do the same page but with the help from the Bootstrap framework.
Are you excited? So let's have a look.
1. Create git branch called hello-b
2. Create there index.html file. Content of the file is [here](https://getbootstrap.com/docs/5.0/getting-started/introduction/#starter-template). Select Option 1, i.e. mini bundle js.
3. Create index.css file and link it
4. Create index.js and link it
5. Add background image which will cover whole page.
6. Add header to the index.html.
    1. margin on the top will be of [size 1](https://getbootstrap.com/docs/5.0/utilities/spacing/#notation)
    2. add hx with text 'Tea Gallery' aligned to the left
    3. add [input with button on the right side](https://getbootstrap.com/docs/5.0/forms/input-group/#button-addons) alligned to the [right](https://getbootstrap.com/docs/5.0/utilities/float/). The button will have space from right of [size 2](https://getbootstrap.com/docs/5.0/utilities/spacing/#notation)
    4. when I click on the button, the alert will display the entered text
7. Add section with text in the [middle of the page](https://getbootstrap.com/docs/5.0/utilities/position/) saying 'Under construction...' (or something else).
8. Add footer to the [bottom](https://getbootstrap.com/docs/5.0/helpers/position/) with • Kate • 2020 centered and with different color.

Your index.css file will contain max. 2 style entries for the [background image](https://www.w3schools.com/howto/howto_css_full_page.asp). All other styling must be done by the Bootstrap styling classes.
Feel free to ask any question.
Good luck
M.

**Comment by knovakova** [comment]
Finished!

**Comment by mihal** [comment]
Good job.
1. Add [icon fonts (install section)](https://icons.getbootstrap.com/) into index.html
2. Enrich the 'Under Construction...' text with some icon and make it blue. Hint: How to use the icon can be seen in icon detail, e.g. [here](https://icons.getbootstrap.com/icons/wallet/)
3. Add [Toast](https://getbootstrap.com/docs/5.0/components/toasts/#custom-content) to the right bottom corner. How to place it can be seen [here](https://getbootstrap.com/docs/5.0/components/toasts/#custom-content). (It is just wrapping the toast to the package called div, which is then positioned in similar manner how the under construction text)
4. Update the handleButtonClick JS function to display the toast with the entered message. How to make it visible by JS is [here](https://getbootstrap.com/docs/5.0/components/toasts/#usage) and [here](https://getbootstrap.com/docs/5.0/components/toasts/#show).

That is all for today.
Good luck.
M.

**Comment by knovakova** [comment]
Finished!

**Comment by mihal** [comment]
Good job, Kate.
