### ISSUE TITLE
8. Real thing - index page

### ISSUE THREAD

**Issue by mihal** [mihal/tea-gallery#8]
Hello Kate,

we will now start to work on your tea gallery.
So let's get started.
1. Create and checkout branch called v1
2. Create index.html file. Content of the file is [here](https://getbootstrap.com/docs/5.0/getting-started/introduction/#starter-template). Select Option 1, i.e. mini bundle js.
3. Add header 
   1. Add clickable hx with text Tea-gallery, i.e. when you click on the header, it will redirect you to the index.html page
4. Add section
   1. Add hx (x >= 3) with text similar to 'Welcome to my tea gallery'
   2. Add paragraph with lorem ipsum text. Lot's of generators online.
   3. Add another paragraph with centered (primary) button saying 'Let's have a look on my collection'
5. Add footer
   1. Centered text (span) saying 'Created by Kate'
6. Create css folder
7. Add common.css file into the css folder and set style
   1. header tag - border bottom - solid blackish 2px
   2. footer tag - border top - solid grayish 2px
8. Link the common.css to the index.html page

We will do just basic styling so we just got the feeling. It does not have to be perfect. Final styling can be done last.
Good luck.

M.

**Comment by knovakova** [comment]
Finished, sir!

**Comment by mihal** [comment]
OK. That's a good start.
