### ISSUE TITLE
9. Real thing - collection page

### ISSUE THREAD

**Issue by mihal** [mihal/tea-gallery#9]
Hello Kate,
1. create page collection.html
2. create style css/collection.css and link it into collection.html
3. link css/common.css
4. create js/collection.js script and link it near the bootstrap mini js bundle link
3. add header same as in index.html
4. add nav and mark it with class container
   1. Read [grid system](https://getbootstrap.com/docs/5.0/layout/grid/)
   2.  add div inside nav.container and mark it row
   3.  add two div inside the div.row. First mark as col-8 and put there a text alphabet. Second mark as col-4 and put there a text search box.
5. add section with temporary centered text as 'My collection content'
6. add footer same as in

**Comment by knovakova** [comment]
Not sure it's exactly like you wanted but I gave it my best shot.

**Comment by mihal** [comment]
Hello Kate,
Good job. You had a good point with the container. Let's do some adjustments.
1. Let's change .container to .container-fluid in the nav element
2. The section as a whole should not centered. There should be some element inside holding a text e.g. span which should be then centered. The section should not have any positioning.
3. We do the navigation bar just a little bit prettier by adding padding top and down by size 2 to the div.row.
4. We replace ''search box'' text with [button input](https://getbootstrap.com/docs/5.0/forms/input-group/#button-addons) 
5. We add id 'alphabet-container' on the container with the text '''alphabet''
6. We move onto the Alphabet generation. We could do that by manually adding 26 letters (buttons). We are better than that, we will do it automatically by little of javascript. I prepared for you tasks inside the collection.js.

Good luck and happy coding.
M.

**Comment by knovakova** [comment]
Finished! (Maybe the span isn't correct but I couldn't find any other way)

**Comment by mihal** [comment]
Hello Kate,
good job. Let's make some cleaning, little bit of styling and another progress.
1. Remove all TODO's which are done. It is important have your code clean without any confusion. 
2. In script collection.js all vars can replaced by ECMA6 variants. Can you figure out how? Sufficient overview is [here](https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/).
3. Reformat collection.html
4. Add same border as is in header under the nav section. The final state is that nav has border on the top and on the bottom.
5. Add "m-1" class into the alphabet button
6. Change current margin of the search input also to the "m-1" so we have them in similar height.
7. Add padding 0.5 em to body style.
8. Let's do some adjustments to our main section
   1. Let's make our section a fluid container
   2. Insert inside two rows with one column in each of them, ([Grid](https://getbootstrap.com/docs/5.0/layout/grid/))
   3. Into the first row/column place a [Breadcrumb](https://getbootstrap.com/docs/5.0/layout/grid/) with just one active item called "Companies" with link directing to the collection.html
   4. Into the second row/column put the centered original span. (The one with the text)

Good luck.
M.

**Comment by knovakova** [comment]
Finished! Additionally, I changed the alphabet col width and remove the col width of search (it should update automatically).

**Comment by mihal** [comment]
Hello Kate,

yes, it looks good. Good job Kate.

1. Add padding of size 3 on section html tag
2. Second div.row. 
   1. Mark with id collectibles-container.
   2. Add classes row-cols-auto and gy-3. Do you know what the two last classes do?
   3. Completely remove the inner div.col.
3. Create a div container with class invisible on the bottom of the page before the script loading. It will be ours template container. 
   1.  Inside add col.div and mark it with company-template
   2.  Inside the company-template add [card](https://getbootstrap.com/docs/5.0/components/card/#titles-text-and-links).
       1. Remove all inside div.card-body except p.card-text. The p.card-text will be empty and has class company-name.
       2. Div.card will have class company-card and text-center
4. Collections.css
    1. Add class company-card and set width and height to 7em. 
    2. Add for all children of .company-card marked with .company-name have margin-top 35%
5. Copy 5 times #company-template code inside collectibles-container. Don't forget to remove id from each of the clones and also don't forget to put some name inside .company-name. What can you see?
6. Zoom in the page. Can you see the footer is stuck on the bottom. Can we make it flow with the scroll? When the companies go under the view-port the footer should go with them too.

Good Luck.
M.

**Comment by knovakova** [comment]
I'm sorry but I can't solve the footer problem. I tried googling and tried a lot of things but nothing does what you want it to do. I've pushed what I have so far (should be everything except the last point).

**Comment by mihal** [comment]
Hello Kate,

it is alright. We will leave the footer for now.
1. Is the footer in index.html the same?
2. Look at the collection.js script and solve all the TODOs.

Happy solving.
M.

**Comment by knovakova** [comment]
Finished!

**Comment by mihal** [comment]
Great Kate. I will close this one a we will be using different format. I will always create a Pull request for you. You will see all the changes made by me there, so it will be easier for you to solve the challenges. Also I can then make a review there. 
After everything is done, either you or me will merge the PR.
See you soon.

M.
